### ISSUE TITLE
BDM | Page | Service > Content & Design | Content

### ISSUE THREAD

**Issue by danaholdt** [beacondig/site-beacon#107]
**NOTE:** Add this to the page epic

## Accelo Content Entry Task: https://beacon-digital-marketing.accelo.com/?action=view_task&id=24442

**Copy Deck:** https://docs.google.com/document/d/19TY4TavRI-AHNbmdhXbMBi3ii3-5aihdXcujD7L8Q0k/edit?usp=sharing
**Staging:** http://2883648-hs-sites-com.sandbox.hs-sites.com/service/content-design-production?hs_preview=NDiluHax-35548892519
**Page Editor:** https://app.hubspot.com/content/2883648/edit/35548892519

@Diksha-Beacon 

Please pour the copy into this page. Use image placeholders for now.

**Comment by Diksha-Beacon** [comment]
Hey @danaholdt 
I have added the provided content and figured out that there is no option to add the hover content for the Services Cards.
Hover effect is also not there. 
Can you please check once & share your feedback.

Thanks

**Comment by danaholdt** [comment]
@Diksha-Beacon -- the link is dynamically generated based on if it has a valid link associated from the "link to" item at the top of the "card options" section 

You can see that now in effect on this page: https://app.hubspot.com/content/2883648/edit/35548892519/content

**Comment by danaholdt** [comment]
@Diksha-Beacon Please always change the LABEL on the task to "in progress" when you actively start working on a task.

**Comment by Diksha-Beacon** [comment]
@danaholdt  thanks for the confirmation and I will take care of label in future.
