### ISSUE TITLE
BDM | Page | Service > Performance Marketing | Content

### ISSUE THREAD

**Issue by danaholdt** [beacondig/site-beacon#109]
**NOTE:** Add this to the page epic

## Accelo Content Entry Task: https://beacon-digital-marketing.accelo.com/?action=view_task&id=24442

**Copy Deck:** https://docs.google.com/document/d/117AUYQl69vihOGY90yx6BKAEjB9mwaLjJTjYwy_vSQk/edit?usp=sharing
**Staging:** http://2883648-hs-sites-com.sandbox.hs-sites.com/service/creative-design-1?hs_preview=NqAMGPJs-35549679615
**Page Editor:** https://app.hubspot.com/content/2883648/edit/35549679615

@Diksha-Beacon 

Please pour the copy into this page. Use image placeholders for now.

**Comment by Diksha-Beacon** [comment]
Hello @danaholdt

I have added the content and following things are pending -

1. Services Icons.
2. Tools Images/icons.
3. Related resources content
4. Employee Quote
5. Service page links.

Thanks
