### ISSUE TITLE
BDM | Page | Services > Content & Design > Video Production | Content

### ISSUE THREAD

**Issue by danaholdt** [beacondig/site-beacon#111]
**NOTE:** Add this to the page epic

## Accelo Content Entry Task: https://beacon-digital-marketing.accelo.com/?action=view_task&id=24442

**Copy Deck:** https://docs.google.com/document/d/1isqvknznfDVUhxxnbv8js6KzohMQKzrgUcTXpBmUIwQ/edit?usp=sharing
**Staging:** http://2883648-hs-sites-com.sandbox.hs-sites.com/-temporary-slug-e7f9c99c-3636-4933-82c7-328e44465d91?hs_preview=vXgJsGxr-37037752907
**Staging Page Editor Link:** https://app.hubspot.com/content/2883648/edit/37037752907/content
**Page Editor:** https://app.hubspot.com/content/2883648/edit/35713730916 

@Diksha-Beacon 

The page in Hubspot is set up to be a template for these page.  You need to clone this first

Steps:
- [x] Clone this page: https://app.hubspot.com/content/2883648/edit/35713730916
- [x] Pour the content
- [x] Add the staging link to this task.

**Comment by Diksha-Beacon** [comment]
Hey @danaholdt 

I have added the content.
Can you please check once & share y our feedback.
And following things are pending -

1) Blockquote
2) Right Column Fields data.

Thanks
