### ISSUE TITLE
BDM | Page | Service > Content & Design > Brand Identity | Content

### ISSUE THREAD

**Issue by danaholdt** [beacondig/site-beacon#112]
**NOTE:** Add this to the page epic

## Accelo Content Entry Task: https://beacon-digital-marketing.accelo.com/?action=view_task&id=24442

**Copy Deck:** https://docs.google.com/document/d/1B4UjYko5gljvKeE81vdCyvnGeWlOft6u-u4nRoe2vHc/edit?usp=sharing
**Staging:** http://2883648-hs-sites-com.sandbox.hs-sites.com/-temporary-slug-a6e58e06-e174-49f0-9956-b1ead18dc6dc?hs_preview=umHmcylH-37039846950
**Staging Page Editor Link:** https://app.hubspot.com/content/2883648/edit/37039846950/content
**Page Editor:** https://app.hubspot.com/content/2883648/edit/35713730916 

@Diksha-Beacon 

The page in Hubspot is set up to be a template for these page.  You need to clone this first

Steps:
- [x] Clone this page: https://app.hubspot.com/content/2883648/edit/35713730916
- [x] Pour the content
- [x] Add the staging link to this task.

**Comment by Diksha-Beacon** [comment]
Hey @danaholdt 

I have added the content.
Can you please check once & share your feedback.
And following things are pending -
1. Blockquote
2. Right Column Fields data.

Thanks
