### ISSUE TITLE
BDM | Page | Resource Single (Ungated) | QA

### ISSUE THREAD

**Issue by dbeau79** [beacondig/site-beacon#143]
**NOTE:** Add this to the page epic

## Accelo QA Task: 

**Client Google Drive:** 
**Figma Wireframes:** 
**Figma Design: https://www.figma.com/file/W8aDuuIxhO6ZUtzEot5rYU/BDM-%7C-Website-Redesign?node-id=515%3A38998&viewport=187%2C253%2C0.015625
**Copy Deck:** 
**Design Assets:**
**Staging: https://www.beacondigitalmarketing.com/sandbox-blog/blog-1-0-0-0-0-0

## People Responsible
**Project Manager:** 
**UX:** 
**Design:** 
**Developer:** 
**QA:** 
**Content:**
**Launch:**

#### DESKTOP
1. Windows 10.0
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Edge
- [x] IE11 (ONLY CRITICAL ISSUES)

2. Windows 7.0
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Edge
- [x] IE11 (ONLY CRITICAL ISSUES)

3. macOS 10.15: Catalina
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Safari

4. macOS 10.14: Mojave
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Safari

5. macOS 10.13: High Sierra
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Safari

#### MOBILE
6. iPhone iOS 13.6
- [x] Safari
- [x] Chrome

7. iPhone iOS 13.5
- [x] Safari
- [x] Chrome

8. iPhone iOS 12.4
- [x] Safari
- [x] Chrome

9. Samsung Galaxy
- [x] Native Browser
- [x] Chrome
  
10. Google Pixel
- [x] Native Browser
- [x] Chrome

**Comment by mccoy-beacon** [comment]
**Suggestion: Keep the main content area at full width below 1200px**

What happens at 1199px:
![chrome_2020-11-06_13-00-09.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/14ff0c51-b575-4b9a-8763-998511ec4bec)

Instead keep at full width like >1200px:
![chrome_2020-11-06_12-59-57.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/626e6455-d685-4a60-acd4-c49986688304)

**Fix: Subscribe Box**
![subscribe-box.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/fa0d0c3d-afe0-4f16-a4e2-f2567f6f3ed9)

**Fix: Switch to full width single-column layout for tablet screensize**
![chrome_2020-11-06_13-56-45.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/32f600c8-5339-4e6d-8de6-41d30c335f25)

**Fix: at 767px strange arrows show up**
![chrome_2020-11-06_13-58-27.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/2a560c99-c698-4e87-9904-7c7e46c0a38f)

**Fix: Extreme amounts of padding on mobile**
![chrome_2020-11-06_14-00-02.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/7471242a-72d1-4187-8c19-f47879cb1438)

**Fix: Very Large Heading Font on Mobile**
![chrome_2020-11-06_14-03-14.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/07551ab1-6206-4667-a9df-336988ab93c0)

**Fix: Thin grey lines on right side on mobile**
![chrome_2020-11-06_14-04-04.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/f88e1bf1-3718-414b-9ec8-b68d223b3ac1)

This is my initial run-through on Windows 10 Chrome. Will take a look at the other browsers when these items are addressed to conserve time.

**Comment by dbeau79** [comment]
@mccoy-beacon thanks for the initial run through.  I made all the suggested updates.
