### ISSUE TITLE
BDM | BUG | Issue with Layout, Card Hover & Quote Image | IE -11 | Windows 10 & 7

### ISSUE THREAD

**Issue by Diksha-Beacon** [beacondig/site-beacon#152]
**Location of bug**
Seen here: http://2883648-hs-sites-com.sandbox.hs-sites.com/why?hs_preview=aciKSlAj-36762777680

**Describe the bug**
1) Layout not coming okay
2) Card hover is displaying the mirror image and not the hover content
3) Quote image is not coming okay

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/32352938-94d7-43b4-a0b9-f145d3402d43)

![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/022f2ab7-8d17-434f-bba4-d2a422b2cf09)

![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/0a7dd638-5d43-4a8e-9940-e528e405144d)

**Desktop (please complete the following information):**
 - OS: Windows 7 & 11
IE-11

**Comment by dbeau79** [comment]
@Diksha-Beacon I changed the flip effect for a simple hide/show in IE.  The other items were resolved as well.

**Comment by Diksha-Beacon** [comment]
@dbeau79 yes it is working fine now.
I am closing the task.

**Comment by Diksha-Beacon** [comment]
@danaholdt This task is already closed.
I have unassigned me.
