### ISSUE TITLE
BDM | BUG | Scrolling Issue | Chrome | macOS 10.13: High Sierra

### ISSUE THREAD

**Issue by Diksha-Beacon** [beacondig/site-beacon#153]
**Location of bug**
Seen here: http://2883648-hs-sites-com.sandbox.hs-sites.com/why?hs_preview=aciKSlAj-36762777680

**Describe the bug**
On scroll, page is getting distorted for a sec & sections are overlapping with each other

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/5f22de26-a684-4260-ba6f-281d17d7dbe7)

![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/170eb7be-54a5-43c2-8f02-666a1d37a4aa)

**Desktop:**
 - macOS 10.13: High Sierra

**Comment by dbeau79** [comment]
@Diksha-Beacon I think this was happening because some of the stock images I used were enormous.  I replaced them with smaller images.  Can you check it again?

**Comment by Diksha-Beacon** [comment]
@dbeau79 Issue is still there. 
Some sections are still overlapping on scroll.

**Comment by Diksha-Beacon** [comment]
@danaholdt @dbeau79  This is fixed.
I am closing the task
