### ISSUE TITLE
BDM | BUG | Verify the Layout | Chrome & Safari

### ISSUE THREAD

**Issue by Diksha-Beacon** [beacondig/site-beacon#154]
**Location of bug**
Seen here: http://2883648-hs-sites-com.sandbox.hs-sites.com/why?hs_preview=aciKSlAj-36762777680

**Describe the bug**
Verify the Layout  

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/d8888d7d-2884-40ed-b7c3-473a28d00cf3)

**Smartphone:**
- Common for all devices

**Comment by dbeau79** [comment]
@Diksha-Beacon the items are supposed to be left aligned but I did add some vertical spacing in between

**Comment by Diksha-Beacon** [comment]
@dbeau79 If it is supposed to be left aligned then I am good with layout.
Closing the issue.
