### ISSUE TITLE
BDM | BUG | Wordpress Staging Server Cleanup

### ISSUE THREAD

**Issue by danaholdt** [beacondig/site-beacon#159]
@mccoy-beacon 

Please 

- [x] disconnect the TDI subdomain 
- [x] provide a list of all active subdomains within beacondigitalmarketing.net
- [x] Make sure all staged sites have blocked SEO crawling 

We need to look at setting up passwords for any non-WP sites in the future.

**Comment by mccoy-beacon** [comment]
@danaholdt 

Current sub-domains still on beacondigitalmarketing.com

archives.
behalf.
behalfresources.
empiredev.
modo-stage.
review.
stripe.

current active sub-domains on new beacondigitalmarekting.net

demo.
essen.
modo-emails.
modo-old.
modo.

I have password protected all the current active sub-domains on beacondigitalmarketing.net

**Comment by danaholdt** [comment]
@mccoy-beacon 

Thanks. just checking that you have also added a noindex, nocrawl to those pages? 

Let's go ahead and do the same with the following on the .com

- [ ] behalf
- [ ] behalfresources
- [ ] empiredev
- [ ] modo-stage

**Comment by mccoy-beacon** [comment]
@danaholdt Remove the sites on the .com or password protect? We can probably just remove those as I dont believe any of those are clients anymore AND modo is on the .net site now. What do you think?

**Comment by danaholdt** [comment]
Go for it!

**Comment by mccoy-beacon** [comment]
@danaholdt Old sites on .com have been removed. This should complete this task.
