### ISSUE TITLE
BDM | Page | All Pages | Design

### ISSUE THREAD

**Issue by danaholdt** [beacondig/site-beacon#162]
Hey @jayepg ---

This task is an optimization task for you. The images in Hubspot are absolutely ginormous. Especially those used in the blogs. Could you:

- [ ] Export all assets in the File Manager for our HS instance (https://app.hubspot.com/files/2883648) ... the option is right under the big orange button
- [ ] Find the giant images
- [ ] reduce their darn butts
- [ ] replace the original file with the smaller image
- [ ] profit

This will take some time. Do this OVER the course of the next two weeks as you can.
Thanks!

**Comment by jayepg** [comment]
Sounds good!
