### ISSUE TITLE
BDM | Page | Service Pages | Asset Collection

### ISSUE THREAD

**Issue by danaholdt** [beacondig/site-beacon#177]
@jayepg -- Whitney has compiled a list of logos we need to collect for the services sections. Could you compile all of these logos (preferably as SVGs and if not that, then as high-resolution color PNGs), resize them to be similar in ration to another, export them and upload them to this folder: https://app.hubspot.com/files/2883648/?folderId=37391006144&showDetails=37374215849

### logos to collect
-----------------------

Tools Section for BDM Website

**Strategy and Analysis**

- [x] HubSpot
- [x] ZoomInfo
- [x] DemandBase
- [x] TechTarget
- [x] Google Data Studio
- [x] Supermetrics
- [x] Ahrefs
- [x] Crystal Knows
- [x] Google Analytics

**Marketing Automation/Tech**

- [x] HubSpot
- [x] Marketo
- [x] Pardot
- [x] Salesforce
- [x] Eloqua
- [x] Drift

**Performance Marketing**

- [x] Google Ads
- [x] Facebook Ads
- [x] Linkedin Ads
- [x] StackAdapt
- [x] RollWorks
- [x] Shape
- [x] Google Analytics
- [x] SEM Rush
- [x] ahrefs
- [x] Moz

**Website Design & Development**

- [x] Figma
- [x] HubSpot
- [x] Wordpress
- [x] HotJar
- [x] Visual Studio
- [x] Marketo
- [x] Pardot
- [x] GitHub
- [x] WP Engine

**Content/Design (Logos)**

- [x] Adobe PhotoShop
- [x] Adobe Illustrator
- [x] Adobe inDesign
- [x] Canva
- [x] Final Cut Pro
- [x] Figma

**Comment by jayepg** [comment]
@danaholdt Hey for some reason I don't have access to that Hubspot folder :D...

**Comment by jayepg** [comment]
This is complete! They're uploaded to that folder.
