### ISSUE TITLE
BDM | Page | Home/Why | Design

### ISSUE THREAD

**Issue by dbeau79** [beacondig/site-beacon#189]
**NOTE:** Add this to the page epic

## Accelo Design Task:

**Client Google Drive:** 
**Figma Wireframes:** 
**Figma Design:**
**Copy Deck:** 
**Design Assets:**
**Staging:** 

## People Responsible
**Project Manager:** 
**UX:** 
**Design:** 
**Developer:** 
**QA:** 
**Content:**
**Launch:**

Hey @jayepg ,

Need your help with an image.  On the homepage (https://2883648-hs-sites-com.sandbox.hs-sites.com/home) we need an icon for the Creative & Design card in the "Where We Shine" section.  

Also, Whitney asked me to change up the badge section a bit and wants to pull in the badge info.  I just added it as an h6 under the badge ( you can see it here: https://2883648-hs-sites-com.sandbox.hs-sites.com/why-hire-digital-agency).  Would you give it a different treatment?

Thanks

**Comment by jayepg** [comment]
@dbeau79 Here you go! Icon: https://share.getcloudapp.com/Blu19p8w


Also, I think the H6 under the badge looks great!
