### ISSUE TITLE
BDM | BUG | Adjust padding so the author info is in line with the text above

### ISSUE THREAD

**Issue by mccoy-beacon** [beacondig/site-beacon#193]
All browsers on desktop:
Adjust padding so the author info is in line with the text above. This happens at 999px when the layout changes.![chrome_2020-11-12_12-29-34.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/00cb6623-00c7-4ac5-a557-447eaa683f91)

**Comment by dbeau79** [comment]
@mccoy-beacon I fixed the padding, thanks
