### ISSUE TITLE
BDM | BUG | Missing Contact us button

### ISSUE THREAD

**Issue by JbuchbinderBeacon** [beacondig/site-beacon#203]
**Location of bug**
Seen here: [ http://2883648-hs-sites-com.sandbox.hs-sites.com/industries?hs_preview=OOryCZzZ-36822733708 ]

**Describe the bug**
Missing contact us button

**Screenshots**
![WP___Industries-3.png](https://images.zenhubusercontent.com/5e9da4f2b51ccc143fa8a8b0/45b6d242-8756-4d41-b6fe-29a45e64a404)

**Desktop (please complete the following information):**
All Version

**Comment by dbeau79** [comment]
@JbuchbinderBeacon this will be handled when content is entered.
