### ISSUE TITLE
BDM | BUG | Remove transition to smaller container below 1199px

### ISSUE THREAD

**Issue by mccoy-beacon** [beacondig/site-beacon#216]
**Location of bug**
Seen here: https://www.beacondigitalmarketing.com/sandbox-ebooks/ebook

Suggestion: at 1199px instead of switching to very narrow content container keep full width like as seen at 1200px

Current View:
![chrome_2020-11-13_10-22-03.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/c9148f23-c8c4-4e4d-add7-d57ecd8ec454)

Desired View:
![chrome_2020-11-13_10-22-12.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/99544702-074b-49af-a001-bc95bb5a0531)

**Comment by dbeau79** [comment]
@mccoy-beacon thanks for the suggestion..implemented
