### ISSUE TITLE
BDM | BUG | Client cards should be rectangular

### ISSUE THREAD

**Issue by JbuchbinderBeacon** [beacondig/site-beacon#225]
**Location of bug**
Seen here: [ http://2883648-hs-sites-com.sandbox.hs-sites.com/industries/cyber-security-marketing-agency?hs_preview=puPnlyzt-36824989253 ]

**Describe the bug**
Client cards should be rectangular

**Screenshots**
![Image from iOS (23).png](https://images.zenhubusercontent.com/5e9da4f2b51ccc143fa8a8b0/cf6d184a-a79f-4b9b-a4ab-29413366fd30)

**Smartphone (please complete the following information):**
 All mobile versions

**Additional context**

**Comment by dbeau79** [comment]
@JbuchbinderBeacon this is happening because the logos (or one of them) are/is square.
