### ISSUE TITLE
BDM | BUG | Missing tabs in page nav bar

### ISSUE THREAD

**Issue by JbuchbinderBeacon** [beacondig/site-beacon#230]
**Location of bug**
Seen here: [ https://2883648-hs-sites-com.sandbox.hs-sites.com/careers?hs_preview=adysPpUc-37024046159# ]

**Describe the bug**
Green bar should have buttons to navigate the page 

**Screenshots**
![Join_Our_Team_of_Digital_Marketers___Beacon_Digital_Marketing.png](https://images.zenhubusercontent.com/5e9da4f2b51ccc143fa8a8b0/74fb4e57-0733-4d18-9488-cff0207744e2)

**Desktop (please complete the following information):**
All versions

**Comment by dbeau79** [comment]
@JbuchbinderBeacon this is a content entry issue, closing it out.
