### ISSUE TITLE
BDM | BUG | Section background should be white, is currenly off white 

### ISSUE THREAD

**Issue by JbuchbinderBeacon** [beacondig/site-beacon#231]
**Location of bug**
Seen here: [ https://2883648-hs-sites-com.sandbox.hs-sites.com/careers?hs_preview=adysPpUc-37024046159# ]

**Describe the bug**
Incorrect color of Background for this section 

**Screenshots**
![Join_Our_Team_of_Digital_Marketers___Beacon_Digital_Marketing-2.png](https://images.zenhubusercontent.com/5e9da4f2b51ccc143fa8a8b0/ea055fe8-e305-47dc-8920-72c74fc5272c)

**Desktop (please complete the following information):**
All versions

**Comment by dbeau79** [comment]
@JbuchbinderBeacon this is a content entry issue, closing it out.
