### ISSUE TITLE
BDM | BUG | Missing section header text

### ISSUE THREAD

**Issue by JbuchbinderBeacon** [beacondig/site-beacon#232]
**Location of bug**
Seen here: [ https://2883648-hs-sites-com.sandbox.hs-sites.com/careers?hs_preview=adysPpUc-37024046159# ]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Join_Our_Team_of_Digital_Marketers___Beacon_Digital_Marketing-4.png](https://images.zenhubusercontent.com/5e9da4f2b51ccc143fa8a8b0/ba2d06b7-b47f-443d-8352-785cbdb661f7)
![Join_Our_Team_of_Digital_Marketers___Beacon_Digital_Marketing-3.png](https://images.zenhubusercontent.com/5e9da4f2b51ccc143fa8a8b0/3d5a586a-cddc-480e-bdad-c87ea00d3334)

**Desktop (please complete the following information):**
All versions

**Comment by dbeau79** [comment]
@JbuchbinderBeacon this is a content entry issue, closing it out.
