### ISSUE TITLE
BDM | BUG | Duplicate Header Items on Rotate

### ISSUE THREAD

**Issue by mccoy-beacon** [beacondig/site-beacon#234]
Seen here: https://2883648-hs-sites-com.sandbox.hs-sites.com/resources?hs_preview=rAdZUTyy-37118193794

When changing the size of the screen from tablet size back to desktop or (see gif below) when viewing on an IPad and rotating from portrait view to landscape view there are duplicate Hire Us buttons and right angle icons added in the header.

![2020-11-13_16-17-51.gif](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/9c292e2d-f297-402f-9c9b-d4ccdcf24b4b)

**Comment by dbeau79** [comment]
@mccoy-beacon this one is resolved
