### ISSUE TITLE
BDM | Page | Services | Functional QA

### ISSUE THREAD

**Issue by danaholdt** [beacondig/site-beacon#78]
PAGE PREVIEW : http://2883648-hs-sites-com.sandbox.hs-sites.com/services?hs_preview=pjAXdKCz-35573641199

@Diksha-Beacon Please do a FUNCTIONAL QA of this page. The pages are not linked, we just want to know where the page is breaking functionally. Not a content QA.

#### DESKTOP
1. Windows 10.0
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Edge
- [x] IE11 (ONLY CRITICAL ISSUES)
2. Windows 7.0
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Edge
- [x] IE11 (ONLY CRITICAL ISSUES)
3. macOS 10.15: Catalina
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Safari
4. macOS 10.14: Mojave
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Safari
5. macOS 10.13: High Sierra
- [x] Chrome (Most Recent)
- [x] FireFox (Most Recent)
- [x] Safari
#### MOBILE
6. iPhone iOS 13.6
- [x] Safari
- [x] Chrome
7. iPhone iOS 13.5
- [x] Safari
- [x] Chrome
8. iPhone iOS 12.4
- [x] Safari
- [x] Chrome
9. Samsung Galaxy
- [x] Native Browser
- [x] Chrome

10. Google Pixel
- [x] Chrome

**Comment by danaholdt** [comment]
@Diksha-Beacon - Please attach all issues you found for this page as blockers to this task.

**Comment by Diksha-Beacon** [comment]
@danaholdt I have attached the issues for this page as blockers to this task.
