### ISSUE TITLE
BDM | BUG | Extra line coming in Banner Slider

### ISSUE THREAD

**Issue by Diksha-Beacon** [beacondig/site-beacon#81]
**Location of bug**
http://2883648-hs-sites-com.sandbox.hs-sites.com/services?hs_preview=pjAXdKCz-35573641199

**Describe the bug**
Extra line coming in Banner Slider on Drag and outline coming on dots on click.

**Screenshots**
https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/40967489-d067-479e-b211-de336acab76d

https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/05e989d4-3d87-4553-9f11-f3b08354a0d7

**Device:**
Common on all devices in windows

**Comment by dbeau79** [comment]
@Diksha-Beacon I removed the line and updated the focus state of the slider dots.

**Comment by Diksha-Beacon** [comment]
@dbeau79 Issue is fixed, closing the task.
