### ISSUE TITLE
BDM | BUG | Tab title is getting underlined

### ISSUE THREAD

**Issue by Diksha-Beacon** [beacondig/site-beacon#89]
**Location of bug**
Seen here: http://2883648-hs-sites-com.sandbox.hs-sites.com/-temporary-slug-1838d8f4-a9a0-4702-9358-299a9dd40aa3?hs_preview=elsQihjr-35713730916

**Describe the bug**
Title is getting underlined on selecting the different tabs in all the browsers and in Firefox along with the title underline, border is also coming 

**Screenshots**

Chrome - 

![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/83f0ba7b-0bb8-4d2b-926b-b5f6d5409dee)

Firefox (Windows)-

![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/1bea8e79-216a-4821-bfe1-6ee435bde0ee)

Firefox (macOS) - 
![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/dea8c663-307f-442c-adb3-dd9a7adddaa5)

**Desktop:**
Common  issue for Windows and macOS

**Comment by dbeau79** [comment]
@Diksha-Beacon I removed the underline and the focus border in FF.

**Comment by dbeau79** [comment]
@Diksha-Beacon I reversed course here and added the focus style back but styled it better.  I think we should keep this for accessibility reasons.

**Comment by Diksha-Beacon** [comment]
@dbeau79 It is working fine now.
I am closing the task.
