### ISSUE TITLE
BDM | BUG | Spacing Required

### ISSUE THREAD

**Issue by Diksha-Beacon** [beacondig/site-beacon#90]
**Location of bug**
Seen here: http://2883648-hs-sites-com.sandbox.hs-sites.com/-temporary-slug-1838d8f4-a9a0-4702-9358-299a9dd40aa3?hs_preview=elsQihjr-35713730916

**Describe the bug**
There is no spacing between text and arrows in the banner and then quick links text.

**Expected behavior**
Need proper spacing so that it doesn't look odd

**Screenshots**

Banner - 
![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/855239f3-bdb3-4dd2-b0a2-f1197424f64d)

Quick Links Text - 
![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/202b8842-66b2-48f5-9c12-0d6952b44731)

**Smartphone:**
Common Issue for Windows & iOS phone

**Comment by dbeau79** [comment]
@Diksha-Beacon both items are fixed.

**Comment by Diksha-Beacon** [comment]
@dbeau79 this is fixed.
Closing the task.
