### ISSUE TITLE
BDM | BUG | Verify the layout

### ISSUE THREAD

**Issue by Diksha-Beacon** [beacondig/site-beacon#91]
**Location of bug**
Seen here: http://2883648-hs-sites-com.sandbox.hs-sites.com/-temporary-slug-1838d8f4-a9a0-4702-9358-299a9dd40aa3?hs_preview=elsQihjr-35713730916

**Describe the bug**
Verify the layout. Currently it is looking very odd.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/64ccaf03-86f3-44df-b90e-b80a56a44bad)

**Smartphone (please complete the following information):**
Common for Windows & iOS device.

**Comment by dbeau79** [comment]
@Diksha-Beacon I updated the tabs header so it is centered on mobile with no dividing line.

**Comment by Diksha-Beacon** [comment]
@dbeau79 It is looking good now.
I am closing the issue.
